#Home Page locators

HomePageSearchEmail="xpath://*[@id='login']/label[1]"
HomePageSearchPassword="xpath://*[@id='login']/label[2]"
HomePageSearchButtonApp="xpath://*[@id='root']/div/div[1]/div[3]/a[2]"
HomePageSearchApps="xpath://*[@id='root']/div/div[8]/div[2]/div[1]/div/div/div[2]/div[2]"
HomePageSearchApp="xpath://h3[text()='Dashport-cambio']"
HomePageSeachIframe="xpath=//*[@id='root']/div/div[5]/div/section/div/div/div[1]/iframe"

#Home Page App
HomePageSeachButtonSave="xpath://*[@id='root']/div/div[2]/div/div/div[2]/div[2]/form/div[4]/div/button/span[1]"
HomePageSeachButtonDelete="xpath://*[@id='root']/div/div[2]/div/div/div[2]/div[2]/form/div[4]/div/button/span[2]"
HomePageSeachModal="xpath://*[@id='root']/div/div[3]/div/div/div[2]/button[1]"
HomePageSeachInputApiKey="xpath://*[@id='root']/div/div[2]/div/div/div[2]/div[2]/form/div[1]/input"
HomePageSeachInputApplicationKey="xpath://*[@id='root']/div/div[2]/div/div/div[2]/div[2]/form/div[2]/input"
HomePageSeachButtonFetch="//*[@id='root']/div/div[2]/div/div/div[3]/div[3]/button/span[2]"
HomePageSeachPageDatadog="xpath://*[@id='root']/div/div[2]/div/div/div/div[1]/div[1]/div"
HomePageSeachPageAlerts="xpath://*[@id='root']/div/div[1]/div/div[1]/li[3]"
HomePageSeachPageInfrastructure="xpath://*[@id='root']/div/div[1]/div/div[1]/li[4]"
HomePageSeachPageLogs="xpath://*[@id='root']/div/div[1]/div/div[1]/li[5]"
HomePageSeachPageMetrics="xpath://*[@id='root']/div/div[1]/div/div[1]/li[6]"
HomePageSeachPageSynthetics="xpath://*[@id='root']/div/div[1]/div/div[1]/li[7]"
HomePageSeachPageAccounts="xpath://*[@id='root']/div/div[1]/div/div[1]/li[8]"
HomePageSeachPageMigration="xpath://*[@id='root']/div/div[1]/div/div[1]/li[9]"
HomePageSeachPageStatus="xpath://*[@id='root']/div/div[1]/div/div[1]/li[10]"